### ISSUE TITLE
Compatibility of Families with ACL

### ISSUE THREAD

**Issue by karthickannan** [VincentChalnot/SidusEAVModelBundle#23]
I want to know whether the families created using this Bundle are compatible with the Symfony's ACL or not. If it is compatible, let me know how to use them together.

**Comment by VincentChalnot** [comment]
Hello there !
If you use a single Data class for all your families (default behavior), you'll probably need to customize the way the ACL are scoped in Symfony by adding a "family" scope:
https://symfony.com/doc/current/security/acl_advanced.html#scope-of-access-control-entries

But alternatively you can create a data class per family which is quite simple and will allow you to use more advanced features in the end.
I've just updated the documentation to explain this:
https://github.com/VincentChalnot/SidusEAVModelBundle/blob/v1.2.x-dev/Documentation/12-custom_classes.md

Let me know if I can close this comment, thanks.

**Comment by nkarthickannan** [comment]
Thank you for your response. Hopefully it'll address the question I have raised. I have the following questions as well:

1. By families, you mean the Entities (like Product Entity, Customer Entity, Employee Entity etc.), am I right ?
2. From your documentation, I know that there should be a Data class & a Value class. But I'm not able to grasp why do we need them and why these classes are empty?

If this is not the right place to ask such questions, please let me know.

Thanks

**Comment by VincentChalnot** [comment]
The families are services that describes the model of your entities, they are EAV entity "types", so yes, you can create a product family, a customer family, etc.
Generally you want to use an EAV model when you have a **lot** of different families and you don't want to create custom Doctrine entities for each of them.

The data and value classes are used to store the actual data in your database, you need to create them yourself because Doctrine doesn't allow overriding entities easily so it's better to create them in each project.

The classes are empty (appart from the annotations) because all the logic is in the AbstractData and AbstractValue classes.

By the way, you can check this repo if you want a demo of the EAV Model inside a fully featured admin management system:
https://github.com/cleverage/eav-manager-starter-kit

**Comment by nkarthickannan** [comment]
That's awesome !! Thank you Vincent. You can close this issue. If there are any queries, I'll contact you in the future.

**Comment by VincentChalnot** [comment]
There is now a dedicated bundle to handle ACL-like permissions in families and attributes:
https://github.com/VincentChalnot/SidusEAVPermissionBundle
